export const START_FETCHING_GOALS = 'sTART_FETCHING_GOALS';
export const STOP_FETCHING_GOALS = 'STOP_FETCHING_GOALS';
export const UPDATE_GOALS = 'UPDATE_GOALS';
export const ERROR_FETCHING_GOALS = 'ERROR_FETCHING_GOALS';